name: Bug Report
description: Create a report to help us improve
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: "When I call get_data('NY.GDP.MKTP.KD.ZG'), it returns an error..."
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproducible Example
      description: Please provide a code snippet to reproduce the issue.
      render: python
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: wbgapi360 Version
      placeholder: "0.2.1"
    validations:
      required: true
